AWSTemplateFormatVersion: '2010-09-09'

Description: Create an ECS Service with Fargate Launch Type
Parameters:
  EcsTaskRole:
    Description: ARN of the IAM role for Systems Manager (SSM)
    Type: String
    Default: arn:aws:iam::767397897837:instance-profile/EcsTaskRole # Assigned per task definition

Resources:
  MyFargateService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !ImportValue fg-cluster-MyECSFargateCluster  # Reference the cluster from the parameter
      ServiceName: MyFargateService
      LaunchType: FARGATE
      TaskDefinition: !Ref MyfargateTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !ImportValue fg-cluster-PublicSubnet1
            - !ImportValue fg-cluster-PublicSubnet2
          SecurityGroups:
            - !ImportValue fg-cluster-SecurityGroup  # Import the security group from ECS cluster stack
      LoadBalancers:
        - ContainerName: my-container
          ContainerPort: 80
          TargetGroupArn: !ImportValue fg-cluster-TargetGroup  # Import the target group from ECS cluster stack
      DesiredCount: 2

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: MyFargateLogGroup #Assuming you created on the console

  MyfargateTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: my-fargate-task
      RequiresCompatibilities:
        - FARGATE  
      Cpu: '256'  # Specify the CPU requirement for the task (in units)
      Memory: '512'  # Specify the memory requirement for the task (in MiB)
      NetworkMode: awsvpc  # Specify the network mode as 'awsvpc' for Fargate
      ExecutionRoleArn: !Ref EcsTaskRole  # Assign the SSM role to the task definition
      ContainerDefinitions:
        - Name: my-container
          Image: hub.docker.com/repository/docker/tchanela/polished:ViaDora  # Update with your public image URI
          PortMappings:
            - ContainerPort: 80  # Replace with your container port
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: my-container    

Outputs:
  ServiceName:
    Description: Name of the ECS Service
    Value: !Ref MyFargateService
